version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      - springapimysql-net
    environment:
#      - DATABASE_USER=admin
#      - DATABASE_PASSWORD=1234
#      - DATABASE_URL=jdbc:mysql://store2-mysqldb-1:3306/electronicsstore?createDatabaseIfNotExist=true
#      - DATABASE_DRIVER=com.mysql.cj.jdbc.Driver
      - spring.datasource.url=jdbc:mysql://store2-mysqldb-1:3306/electronicsstore

    depends_on:
      - mysqldb

    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3307:3306
    networks:
      - springapimysql-net
    environment:
      MYSQL_DATABASE: electronicsstore
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
    volumes:
      - ./electronicsstore.sql:/docker-entrypoint-initdb.d/electronicsstore.sql
networks:
  springapimysql-net:
